//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Producto_2.Modelo
{
    using System;
    using System.Collections.Generic;
   
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public string NIF { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public byte VIP { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public Nullable<int> cp { get; set; }
        public string pais { get; set; }
        public Nullable<System.DateTime> fechaN { get; set; }
        public string detalle { get; set; }
        public string nombreCuenta { get; set; }
        public string numeroCuenta { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Reservas> Reservas { get; set; }
    }
}
